// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClTjou_mDB4wPlkGBwROjpbnYhfNIiRgA',
    appId: '1:419250487030:web:85f2197881fcd58e13f6d7',
    messagingSenderId: '419250487030',
    projectId: 'riwama-4d9b4',
    authDomain: 'riwama-4d9b4.firebaseapp.com',
    storageBucket: 'riwama-4d9b4.appspot.com',
    measurementId: 'G-9P3Q14W419',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCazJUGhRbpqJ3w0hDys4aJwAwozzrGpeY',
    appId: '1:419250487030:android:354d641415bef08f13f6d7',
    messagingSenderId: '419250487030',
    projectId: 'riwama-4d9b4',
    storageBucket: 'riwama-4d9b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bjxs2z2dzyurfbrc6x5UUX46BuesokM',
    appId: '1:419250487030:ios:ce40133eba6b597d13f6d7',
    messagingSenderId: '419250487030',
    projectId: 'riwama-4d9b4',
    storageBucket: 'riwama-4d9b4.appspot.com',
    iosBundleId: 'com.riwama.app  ',
  );
}
